### ISSUE TITLE
Adding introspection package breaks creating incoming payment

### ISSUE THREAD

**Issue by sabineschaller** [interledger/rafiki#1002]
- #960

broke the Postman demo (Demo with Signatures). I can request and receive a grant to create an incoming payment but when I send the request to actually create the incoming payment, I receive an Internal Server Error. The logs print
```
$ docker logs local-peer-backend-1                                                                                                                                         
{"level":30,"time":1674131143494,"pid":1,"hostname":"b1d9df5f9637","msg":"creating knex"}
info(message_bus): connected to replica 0
{"level":40,"time":1674131145051,"pid":1,"hostname":"b1d9df5f9637","path":"/jwks.json","method":"get","msg":"unexpected path/method"}
{"level":30,"time":1674131145190,"pid":1,"hostname":"b1d9df5f9637","msg":"Admin listening on 3001"}
{"level":30,"time":1674131145191,"pid":1,"hostname":"b1d9df5f9637","msg":"Open Payments listening on 80"}
{"level":30,"time":1674131145191,"pid":1,"hostname":"b1d9df5f9637","msg":"Connector listening on 3002"}
{"level":30,"time":1674131145191,"pid":1,"hostname":"b1d9df5f9637","msg":"🐒 has 🚀. Get ready for 🍌🍌🍌🍌🍌"}
{"level":50,"time":1674131153607,"pid":1,"hostname":"b1d9df5f9637","args":"96A406CE37670106D8D4","msg":"Error when making introspection request: Request failed with status code 415"}
err= Error: Error when making introspection request: Request failed with status code 415
    at introspectToken (/workspace/packages/token-introspection/dist/client/introspection.js:41:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /workspace/packages/backend/dist/open_payments/auth/middleware.js:35:31
    at async /workspace/packages/openapi/dist/middleware.js:17:17
    at async /workspace/packages/backend/dist/open_payments/payment_pointer/middleware.js:16:9
    at async bodyParser (/workspace/node_modules/.pnpm/koa-bodyparser@4.3.0/node_modules/koa-bodyparser/index.js:95:5)

  InternalServerError: Internal Server Error
      at Object.throw (/workspace/node_modules/.pnpm/koa@2.14.1/node_modules/koa/lib/context.js:97:11)
      at /workspace/packages/openapi/dist/middleware.js:35:26
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async /workspace/packages/backend/dist/open_payments/payment_pointer/middleware.js:16:9
      at async bodyParser (/workspace/node_modules/.pnpm/koa-bodyparser@4.3.0/node_modules/koa-bodyparser/index.js:95:5)
```

**Comment by wilsonianb** [comment]
The request from the `token-introspection` package has the wrong `Content-Type` header
```
local-peer-auth-1        | {
local-peer-auth-1        |   method: 'POST',
local-peer-auth-1        |   url: '/introspect',
local-peer-auth-1        |   header: {
local-peer-auth-1        |     accept: 'application/json, text/plain, */*',
local-peer-auth-1        |     'content-type': 'application/x-www-form-urlencoded',
local-peer-auth-1        |     'user-agent': 'axios/1.2.3',
local-peer-auth-1        |     'content-length': '20',
local-peer-auth-1        |     'accept-encoding': 'gzip, compress, deflate, br',
local-peer-auth-1        |     host: 'peer-auth:3006',
local-peer-auth-1        |     connection: 'close'
local-peer-auth-1        |   }
local-peer-auth-1        | }
```
despite
https://github.com/interledger/rafiki/blob/df190d40c0245aee29614771c5514fb06896c055/packages/token-introspection/src/client/index.ts#L52

**Comment by wilsonianb** [comment]
We're just passing the token string to `introspect`
https://github.com/interledger/rafiki/blob/df190d40c0245aee29614771c5514fb06896c055/packages/backend/src/open_payments/auth/middleware.ts#L59
when it takes
https://github.com/interledger/rafiki/blob/df190d40c0245aee29614771c5514fb06896c055/packages/token-introspection/src/client/introspection.ts#L6
https://github.com/interledger/rafiki/blob/df190d40c0245aee29614771c5514fb06896c055/packages/token-introspection/src/types.ts#L3-L4
https://github.com/interledger/rafiki/blob/df190d40c0245aee29614771c5514fb06896c055/packages/token-introspection/src/openapi/generated/types.ts#L68-L76
I'm confused why we're not getting a type error :confused:
