### ISSUE TITLE
Jest: Got error running globalSetup - reason: the database system is starting up

### ISSUE THREAD

**Issue by sabineschaller** [interledger/rafiki#1099]
I sporadically see this in the github actions
```
> backend@ test /home/runner/work/rafiki/rafiki/packages/backend
> jest --passWithNoTests --maxWorkers=50%

error: Jest: Got error running globalSetup - /home/runner/work/rafiki/rafiki/packages/backend/jest.setup.ts, reason: the database system is starting up
    at Parser.parseErrorMessage (/home/runner/work/rafiki/rafiki/node_modules/.pnpm/pg-protocol@1.6.0/node_modules/pg-protocol/src/parser.ts:369:69)
    at Parser.handlePacket (/home/runner/work/rafiki/rafiki/node_modules/.pnpm/pg-protocol@1.6.0/node_modules/pg-protocol/src/parser.ts:188:21)
    at Parser.parse (/home/runner/work/rafiki/rafiki/node_modules/.pnpm/pg-protocol@1.6.0/node_modules/pg-protocol/src/parser.ts:103:30)
    at Socket.<anonymous> (/home/runner/work/rafiki/rafiki/node_modules/.pnpm/pg-protocol@1.6.0/node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Socket.Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
undefined
/home/runner/work/rafiki/rafiki/packages/backend:
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  backend@ test: `jest --passWithNoTests --maxWorkers=50%`
Exit status 1
Error: Process completed with exit code 1.
```
Re-running the job usually works.

**Comment by sublimator** [comment]
> Re-running the job usually works.

The interledgerjs tests were .. less than ideal too. 
Generally people put a retry on flakey tests to keep the CI green (but it can inspire false confidence)
