### ISSUE TITLE
Add instructions to run tests to validate localenv setup

### ISSUE THREAD

**Issue by BlairCurrey** [interledger/rafiki#1424]
Currently there are no instructions to validate setup is complete, such as running tests, in the `localenv/README.md` setup instructions. Presumably `pnpm sanity` should work after setup is complete. Instructions to run this test could be included at the end of the ["Setup" section](https://github.com/interledger/rafiki/blob/main/localenv/README.md#setup). 

The tests should also pass at this point. I mention this because some of them do not for me. I setup using the instructions so something is missing (perhaps what I did, otherwise the docs). 

I get ~70 failed tests on the backend and 1 in auth.

<details>
  <summary>A few of the failing tests from backend:</summary>

  ● Accounting Service › Withdrawal › Void › Cannot void expired withdrawal

    thrown: "Exceeded timeout of 30000 ms for a hook.
    Add a timeout value to this test to increase the timeout, if this is a long-running test. See https://jestjs.io/docs/api#testname-fn-timeout."

      33 |   }
      34 |
    > 35 |   beforeAll(async (): Promise<void> => {
         |   ^
      36 |     const { port } = await startTigerbeetleContainer()
      37 |     Config.tigerbeetleReplicaAddresses = [port.toString()]
      38 |

      at beforeAll (packages/backend/src/accounting/tigerbeetle/service.test.ts:35:3)
      at Object.describe (packages/backend/src/accounting/tigerbeetle/service.test.ts:23:1)

  ● Accounting Service › Withdrawal › Void › Cannot void expired withdrawal

    TypeError: Cannot read properties of undefined (reading 'knex')

      44 |
      45 |   afterEach(async (): Promise<void> => {
    > 46 |     await truncateTables(appContainer.knex)
         |                                       ^
      47 |   })
      48 |
      49 |   afterAll(async (): Promise<void> => {

      at Object.knex (packages/backend/src/accounting/tigerbeetle/service.test.ts:46:39)

  ● Test suite failed to run

    TypeError: Cannot read properties of undefined (reading 'shutdown')

      48 |
      49 |   afterAll(async (): Promise<void> => {
    > 50 |     await appContainer.shutdown()
         |                        ^
      51 |     // TODO: find a way to gracefully stop TB container without running into a thread panic
      52 |   })
      53 |

      at Object.shutdown (packages/backend/src/accounting/tigerbeetle/service.test.ts:50:24)

</details>

https://github.com/interledger/rafiki/issues/1094 seems like it may describe at least the third failure `TypeError: Cannot read properties of undefined (reading 'shutdown')` in the `afterAll` hook of the tigerbeetle service test file.

**Comment by BlairCurrey** [comment]
Closing, as there is a command for running all the tests in the readme. And in hindsight the mentioned test failures are something unique to my local environment.
