### ISSUE TITLE
[BUG] Internal Server Error when redirecting to interaction

### ISSUE THREAD

**Issue by raducristianpopa** [interledger/rafiki#2826]
## Bug Report

**Describe the bug**

After an interactive grant is created and an application tries to redirect the user to the URL, there is an `Internal Server Error`.
This is not happening on a regular basis. After the page is refreshed, the user is correctly redirected to the IdP page.

**To Reproduce**

This happened to me when connecting my wallet from Rafiki Money to the Web Monetization Extension

**Expected behavior**

The user should be redirected directly to the IdP page, without having to refresh a page that showcases an Internal Server Error.

**Desktop (please complete the following information):**

 - OS: [e.g. Ubuntu]
 - Version [e.g. 20.04LTS]
 - Node version [e.g. 18.16.0]
 - pnpm version [e.g. 8.6.7]

**Screenshots**
![image](https://github.com/user-attachments/assets/e27626e0-aeee-4dff-bbf1-622eb3a6b652)

**Additional context**
Logs from Rafiki Auth (rafiki.money)

```
  TypeError: option maxAge is invalid
      at new Cookie (/home/rafiki/node_modules/.pnpm/cookies@0.9.1/node_modules/cookies/index.js:182:11)
      at Cookies.set (/home/rafiki/node_modules/.pnpm/cookies@0.9.1/node_modules/cookies/index.js:117:16)
      at ContextSession.save (/home/rafiki/node_modules/.pnpm/koa-session@6.4.0/node_modules/koa-session/lib/context.js:331:26)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async ContextSession.commit (/home/rafiki/node_modules/.pnpm/koa-session@6.4.0/node_modules/koa-session/lib/context.js:244:5)
      at async session (/home/rafiki/node_modules/.pnpm/koa-session@6.4.0/node_modules/koa-session/index.js:46:9)
      at async cors (/home/rafiki/node_modules/.pnpm/@koa+cors@5.0.0/node_modules/@koa/cors/index.js:109:16)
```

**Comment by sabineschaller** [comment]
I was able to reproduce this on the localenv by requesting multiple outgoing payment grants (which require interaction) through Bruno. On the 4th try, I saw the Internal Server Error when opening the redirect link from Bruno.
