### ISSUE TITLE
Dockerize Rafiki backend crashed in MacOS m1 chip

### ISSUE THREAD

**Issue by ProgNovel** [interledger/rafiki#299]
**Issue description**

I tried to build a docker image locally according to https://github.com/interledger/rafiki/tree/main/packages/backend using the command `yarn docker build backend -t rafiki-backend`. The docker soon crashed with the following error:
![rafiki error](https://user-images.githubusercontent.com/45922701/160977869-b464c753-ae8e-41ff-82c1-b1ab0c7875ef.png)

---
**OS version:** MacOS BigSur 11.6
**Hardware:** M1 chip 8GB Ram
**Node version:** v17.7.1 and v14.19.1
**NPM version:** v8.5.2 and vv6.14.16
**Yarn version:** v3.0.2 (locally in Rafiki root folder), and v1.22.15 (globally)

**Comment by ProgNovel** [comment]
I tried fixing the error above by downgrading `bcrypt` dependency to version `5.0.0` as per suggestions in https://github.com/kelektiv/node.bcrypt.js/issues/917. Now Docker able to build the image just fine. 

The problem now is that Docker failed when running the built Rafiki image.
The error I got:
```
Error: Failed to initialize io_uring
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1144:18)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.external_module_.Module._load (/workspace/.pnp.cjs:19603:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/workspace/.yarn/unplugged/tigerbeetle-node-npm-0.4.1-16106fd9d1/node_modules/tigerbeetle-node/dist/index.js:4:17)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.external_module_.Module._load (/workspace/.pnp.cjs:19603:14)
emergency: Failed to initialise environment.

internal/modules/cjs/loader.js:1144
  return process.dlopen(module, path.toNamespacedPath(filename));
```
