### ISSUE TITLE
Insufficient localenv peer liquidity

### ISSUE THREAD

**Issue by wilsonianb** [interledger/rafiki#620]
Attempting to create a quote to an `https://peer-backend/accounts/pfry` incoming payment fails with the following log:
```
local-peer-backend-1  | {"level":20,"time":1663711428919,"pid":1,"hostname":"3d04c8337a1a","service":"ConnectorService","err":{"type":"InsufficientLiquidityError","message":"InsufficientBalance","stack":"InsufficientLiquidityError: InsufficientBalance\n    at /workspace/packages/backend/dist/connector/core/middleware/balance.js:42:27\n    at async ildcp (/workspace/packages/backend/dist/connector/core/middleware/ildcp.js:12:13)\n    at async /workspace/packages/backend/dist/connector/core/middleware/throughput.js:54:9\n    at async /workspace/packages/backend/dist/connector/core/middleware/rate-limit.js:33:9\n    at async /workspace/packages/backend/dist/connector/core/middleware/max-packet-amount.js:22:9\n    at async account (/workspace/packages/backend/dist/connector/core/middleware/account.js:81:9)\n    at async /workspace/packages/backend/dist/connector/core/middleware/stream-address.js:9:9\n    at async /workspace/packages/backend/dist/connector/core/middleware/error-handler.js:14:13\n    at async ilpPacket (/workspace/packages/backend/dist/connector/core/middleware/ilp-packet.js:171:9)\n    at async auth (/workspace/packages/backend/dist/connector/core/middleware/auth.js:31:9)","ilpErrorCode":"T04"},"msg":"Error thrown in incoming pipeline"}
```
I'm guessing the [`initialLiquidity`](https://github.com/interledger/rafiki/blob/main/infrastructure/local/seed.peer.yml#L9) isn't sufficient for the quote's unfulfillable rate probe [packet amounts](https://github.com/interledgerjs/interledgerjs/blob/master/packages/pay/src/senders/rate-probe.ts#L26-L45).

**Comment by wilsonianb** [comment]
- related to #571
