### ISSUE TITLE
Mock account provider quote error

### ISSUE THREAD

**Issue by wilsonianb** [interledger/rafiki#621]
```
{
  id: 'a066a4ab-cbd1-4a73-b911-fadd1087dcf2',
  paymentPointerId: '3807c74e-fcdf-4f6f-a548-c626d49b602b',
  receiver: 'https://peer-backend/accounts/pfry/incoming-payments/70f567d7-1f5e-4e30-9dd1-76903b547a5e',
  sendAmount: { value: '100', assetCode: 'USD', assetScale: 2 },
  receiveAmount: { value: '99', assetCode: 'USD', assetScale: 2 },
  createdAt: '2022-09-20T22:48:27.125Z',
  expiresAt: '1970-01-01T00:00:00.000Z',
  paymentType: 'FixedSend'
}
```
The mock account provider's `/quotes` endpoint gets the following error when processing the above quote
```
local-fynbos-1        | RangeError: The number 1.98 cannot be converted to a BigInt because it is not an integer
local-fynbos-1        |     at BigInt (<anonymous>)
local-fynbos-1        |     at action2 (/workspace/packages/mock-account-provider/build/index.js:514:16)
local-fynbos-1        |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
local-fynbos-1        |     at Object.callRouteAction (/workspace/node_modules/.pnpm/@remix-run+server-runtime@1.6.8_biqbaboplfbrettd7655fr4n2y/node_modules/@remix-run/server-runtime/dist/data.js:40:14)
local-fynbos-1        |     at handleResourceRequest (/workspace/node_modules/.pnpm/@remix-run+server-runtime@1.6.8_biqbaboplfbrettd7655fr4n2y/node_modules/@remix-run/server-runtime/dist/server.js:442:14)
local-fynbos-1        |     at requestHandler (/workspace/node_modules/.pnpm/@remix-run+server-runtime@1.6.8_biqbaboplfbrettd7655fr4n2y/node_modules/@remix-run/server-runtime/dist/server.js:42:18)
local-fynbos-1        |     at /workspace/node_modules/.pnpm/@remix-run+express@1.6.8_nawawpklwqjvxe6axdd7matlce/node_modules/@remix-run/express/dist/server.js:39:22
local-fynbos-1        | POST /quotes 500 - - 7.610 ms
```

**Comment by wilsonianb** [comment]
- related to #571
