### ISSUE TITLE
[Backend] Can't complete incoming payment

### ISSUE THREAD

**Issue by sabineschaller** [interledger/rafiki#695]
```
  InternalServerError: response must NOT have additional properties: ilpStreamConnection
      at Object.throw (/workspace/node_modules/.pnpm/koa@2.13.4/node_modules/koa/lib/context.js:97:11)
      at /workspace/packages/openapi/dist/middleware.js:22:22
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async /workspace/packages/backend/dist/open_payments/auth/middleware.js:55:13
      at async /workspace/packages/backend/dist/open_payments/payment_pointer/middleware.js:12:9
      at async bodyParser (/workspace/node_modules/.pnpm/koa-bodyparser@4.3.0/node_modules/koa-bodyparser/index.js:95:5)
```

**Comment by wilsonianb** [comment]
whoops :upside_down_face: 
https://github.com/interledger/rafiki/blob/92c89a35aca2cfde7903abbef04fcfffb2b6f369/packages/backend/src/open_payments/payment/incoming/routes.test.ts#L269-L273

We can avoid similar issues with:
- https://github.com/interledger/rafiki/issues/594
