### ISSUE TITLE
[Backend] POST Create quote throws 500 if insufficient balance

### ISSUE THREAD

**Issue by sabineschaller** [interledger/rafiki#698]
```
{"level":20,"time":1666839875264,"pid":1,"hostname":"7a99b5046e98","service":"ConnectorService","err":{"type":"InsufficientLiquidityError","message":"InsufficientBalance","stack":"InsufficientLiquidityError: InsufficientBalance\n    at /workspace/packages/backend/dist/connector/core/middleware/balance.js:42:27\n    at async ildcp (/workspace/packages/backend/dist/connector/core/middleware/ildcp.js:12:13)\n    at async /workspace/packages/backend/dist/connector/core/middleware/throughput.js:54:9\n    at async /workspace/packages/backend/dist/connector/core/middleware/rate-limit.js:33:9\n    at async /workspace/packages/backend/dist/connector/core/middleware/max-packet-amount.js:22:9\n    at async account (/workspace/packages/backend/dist/connector/core/middleware/account.js:83:9)\n    at async /workspace/packages/backend/dist/connector/core/middleware/stream-address.js:9:9\n    at async /workspace/packages/backend/dist/connector/core/middleware/error-handler.js:14:13\n    at async ilpPacket (/workspace/packages/backend/dist/connector/core/middleware/ilp-packet.js:171:9)\n    at async auth (/workspace/packages/backend/dist/connector/core/middleware/auth.js:31:9)","ilpErrorCode":"T04"},"msg":"Error thrown in incoming pipeline"}
```
We should improve error handling.

**Comment by wilsonianb** [comment]
I'm pretty a connector insufficient balance error during quote creation would be due to insufficient peer liquidity for the rate probe.

**Comment by wilsonianb** [comment]
fwiw, it's the same error as:
- https://github.com/interledger/rafiki/issues/620

Taking another look at that issue, it looks like our current initial peer liquidity is equal to the largest rate probe amount:
https://github.com/interledger/rafiki/pull/635/files
https://github.com/interledgerjs/interledgerjs/blob/88dfc15860c5f3899fcd7e72921488634389b399/packages/pay/src/senders/rate-probe.ts#L26-L45

So, I think it makes sense that using any amount of that peer liquidity in an outgoing payment would cause a subsequent quote's rate probe to fail.

We could just increase the peer liquidity here, but this seems like a larger issue (https://github.com/interledger/rafiki/issues/205).
Maybe we need to dust off the rate probe code and see if we can use smaller amounts (based on smaller quote amounts?)

**Comment by mkurapov** [comment]
Ah, so even the smallest subsequent payment would fail. I'm not too familiar with the actual connector code, but that makes sense. Do we need to bump #205 then?

**Comment by wilsonianb** [comment]
- Resolved by https://github.com/interledger/rafiki/pull/730

Opened :point_down: for remaining related outgoing payment creation issue
- https://github.com/interledger/rafiki/issues/922
