### ISSUE TITLE
Create outgoing payment throws 500 if insufficient balance

### ISSUE THREAD

**Issue by wilsonianb** [interledger/rafiki#922]
- related to #698 

https://github.com/interledger/rafiki/pull/730#issue-1436605867
>I tested that the quote + outgoing payment flow in Postman can be run twice (2nd quote now succeeds and outgoing payment is created, but never funded due to insufficient balance at map).
Error handling should still be improved for when there's a legitimate insufficient balance error in the connector (which should now only happen with outgoing payments instead of quotes).

**Comment by wilsonianb** [comment]
Outgoing payment creation actually succeeds and the webhook event correctly responds `200` for insufficient balance
```
local-fynbos-1           | received webhook:  {"id":"87682853-be18-47b1-860f-36f68fb53aaf","type":"outgoing_payment.created","data":{"payment":{"id":"d5d54774-a9e0-4071-8dca-257ece25d634","paymentPointerId":"11545236-2ebc-462d-83b4-729179f985ed","state":"FUNDING","receiver":"https://peer-backend/accounts/pfry/incoming-payments/1ac402ec-3bdb-41c5-ba2d-d23014d32d5f","sendAmount":{"value":"3565","assetCode":"USD","assetScale":2},"receiveAmount":{"value":"3364","assetCode":"USD","assetScale":2},"sentAmount":{"value":"0","assetCode":"USD","assetScale":2},"stateAttempts":0,"createdAt":"2023-01-04T22:40:03.978Z","updatedAt":"2023-01-04T22:40:04.026Z","balance":"0","description":"Your purchase at Shoe Shop","externalRef":"#INV2022-8363828","peerId":"9ef60be4-d743-4828-993d-a9e57b38dab6"}}}
local-fynbos-1           | Error: invalid pending debit amount, insufficient funds
local-fynbos-1           |     at AccountProvider.pendingDebit (/workspace/packages/mock-account-provider/build/index.js:378:13)
local-fynbos-1           |     at handleOutgoingPaymentCreated (/workspace/packages/mock-account-provider/build/index.js:2942:22)
local-fynbos-1           |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
local-fynbos-1           |     at action (/workspace/packages/mock-account-provider/build/index.js:3000:9)
local-fynbos-1           |     at Object.callRouteActionRR (/workspace/node_modules/.pnpm/@remix-run+server-runtime@1.9.0_biqbaboplfbrettd7655fr4n2y/node_modules/@remix-run/server-runtime/dist/data.js:24:16)
local-fynbos-1           |     at callLoaderOrAction (/workspace/node_modules/.pnpm/@remix-run+router@1.1.0/node_modules/@remix-run/router/router.ts:2657:14)
local-fynbos-1           |     at submit (/workspace/node_modules/.pnpm/@remix-run+router@1.1.0/node_modules/@remix-run/router/router.ts:2178:16)
local-fynbos-1           |     at queryImpl (/workspace/node_modules/.pnpm/@remix-run+router@1.1.0/node_modules/@remix-run/router/router.ts:2113:22)
local-fynbos-1           |     at Object.queryRoute (/workspace/node_modules/.pnpm/@remix-run+router@1.1.0/node_modules/@remix-run/router/router.ts:2074:18)
local-fynbos-1           |     at handleResourceRequestRR (/workspace/node_modules/.pnpm/@remix-run+server-runtime@1.9.0_biqbaboplfbrettd7655fr4n2y/node_modules/@remix-run/server-runtime/dist/server.js:271:20)
local-fynbos-1           | POST /webhooks 200 - - 57.769 ms
```
